version: '2'
services:
    shinebackend-app:
        image: shinebackend
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://shinebackend-mysql:3306/shinebackend?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    shinebackend-mysql:
        extends:
            file: mysql.yml
            service: shinebackend-mysql
